#### runchunks(to, from, file): replay a slice of a *_chunks.R file.
#### to   = header substring; stop on the line BEFORE it (default: end)
#### from = header substring of the first chunk to run (default: top,
####        including the embedded preamble). eval = F entries skipped.
#### file default = newest *_chunks.R in this folder.
#### generated by extract_chunks.R -- do not edit; regenerate instead.
runchunks <- function(to = NULL, from = NULL, file = NULL) {
  if (is.null(file)) {
    cand <- list.files("C:/data/GUK/analysis/.claude/.scratch/extract_chunks",
      pattern = "_chunks\\.R$", full.names = TRUE)
    if (length(cand) == 0) stop("no *_chunks.R found")
    if (length(cand) > 1) {
      ## disambiguate: keep files whose headers contain to/from targets
      all0 <- cand
      keys <- c(to, from)
      if (length(keys) > 0) {
        hasall <- vapply(cand, function(f2) {
          h2 <- grep("^#### ", readLines(f2, warn = FALSE,
            encoding = "UTF-8"), value = TRUE)
          all(vapply(keys, function(k) any(grepl(k, h2, fixed = TRUE)),
            logical(1)))
        }, logical(1))
        cand <- cand[hasall]
      }
      if (length(cand) != 1)
        stop("ambiguous chunks file; pass file= explicitly:\n  ",
             paste(basename(all0), collapse = "\n  "))
    }
    file <- cand
    message("runchunks: using ", basename(file))
  }
  old <- getOption("knitr.duplicate.label")          # keep old value
  options(knitr.duplicate.label = "allow")            # allow re-runs
  on.exit(options(knitr.duplicate.label = old))       # restore on exit
  L <- readLines(file, warn = FALSE, encoding = "UTF-8")
  ## cwd change is NECESSARY to mock knitr's internal behaviour for these
  ## globalenv() replays: knit()/render() evaluate every chunk with
  ## cwd = the document dir (in_dir(input_dir())), so doc-relative paths
  ## ("../program/x.prn") only resolve from there. Save/set/restore.
  dd <- sub("^#### docdir: ", "", grep("^#### docdir: ", L, value = TRUE)[1])
  if (!is.na(dd)) {
    oldwd <- getwd()                                   # keep old cwd
    setwd(dd)                                          # set document dir
    on.exit(setwd(oldwd), add = TRUE)                  # restore on exit
  }
  hi <- grep("^#### (knit_child:|inline,|.*, lines [0-9]+-[0-9]+)", L)
  hit <- length(L) + 1L
  if (!is.null(to)) {
    hit <- hi[grepl(to, L[hi], fixed = TRUE)][1]
    if (is.na(hit)) stop("'to' not found: ", to)
  }
  lo <- 1L
  if (!is.null(from)) {
    lo <- hi[grepl(from, L[hi], fixed = TRUE)][1]
    if (is.na(lo)) stop("'from' not found: ", from)
    if (lo >= hit) stop("'from' is at or after 'to'")
  }
  keep <- rep(TRUE, hit - lo)
  for (s in hi[hi >= lo & hi < hit]) {
    if (grepl("eval = F", L[s], fixed = TRUE)) {
      e <- hi[hi > s][1]; if (is.na(e) || e > hit) e <- hit
      keep[(s:(e - 1)) - lo + 1L] <- FALSE
    }
  }
  eval(parse(text = L[lo:(hit - 1L)][keep]), envir = globalenv())
}
