vartobetested <- c(
  "HeadLiteracy", "HeadAge", 
  "HHsize", "Arm", "FloodInRd1", 
  "NLHAssetAmount", "PAssetAmount", 
  "TotalImputedValue", "NumCows", "NetValue", "NetBroadValue",
  "RiskPrefVal", "TimePref1Val", "TimePref2Val", "PresentBias")
selection.criteria <- c(
  "Attrited", 
    "Attrited", "Attrited", "TradArm", 
  "Attrited", 
    "Attrited", "Attrited", "TradArm", "CowArm", "CowArm", 
  "Active", 
    "Active", "Active", "TradArm", "CowArm", "CowArm", 
  "Rejected", 
    "Rejected", "Rejected", "TradArm", 
  "GRejected", 
    "GRejected", "GRejected", "TradArm",
  "IRejected", 
    "IRejected", "IRejected", "TradArm", "TradArm",
    "CowArm", "CowArm", "CowArm", "CowArm",
  "TradArm")
addtofilename <- c(
  "Attrited", 
    "AttritedInTrad", "AttritedInNonTrad", "TradNonTradAttrited", 
  "NonFloodAttrited", 
    "NonFloodAttritedInTrad", "NonFloodAttritedInNonTrad", "NonFloodTradNonTradAttrited",
    "NonFloodAttritedCowNonCow", "NonFloodAttritedCowLargeGrace",
  "Active", 
    "ActiveInTrad", "ActiveInNonTrad","ActiveTradNonTrad",
    "ActiveCowNonCow", "ActiveCowLargeGrace",
  "Rejected", 
    "RejectedInTrad", "RejectedInNonTrad", "TradNonTradRejected", 
  "GRejected", 
    "GRejectedInTrad", "GRejectedInNonTrad","TradNonTradGRejected",
  "IRejected", 
    "IRejectedInTrad", "IRejectedInNonTrad","TradNonTradIRejected",
    "GRejectedTradParticipatedNonTrad",
  "RejectedCowNonCow", 
    "RejectedCowLargeGrace", "AcceptedCowNonCow", "AcceptedCowLargeGrace",
  "RandomAssignmentTradNonTrad")
HeaderDescription <- c(
  "Permutation test results of attrition", 
    "Permutation test results of attrition among traditional arm",
    "Permutation test results of attrition among non-traditional arm",
    "Permutation test results of attriters of traditional and non-traditional arms",
  "Permutation test results of non-flood attrition", 
    "Permutation test results of non-flood attrition among traditional arm",
    "Permutation test results of non-flood attrition among non-traditional arm",
    "Permutation test results of non-flood attriters of traditional and non-traditional arms",
    "Permutation test results of non-flood attriters of cattle and all other arms",
    "Permutation test results of non-flood attriters of cattle and large grace",
  "Permutation test results of active status", 
    "Permutation test results of active status among traditional arm",
    "Permutation test results of active status among non-traditional arms",
    "Permutation test results of active members of traditional and non-traditional arms",
    "Permutation test results of active members of cattle and all other arms",
    "Permutation test results of active members of cattle and large grace arms",
#  "Permutation test results of attrition among borrowers", 
#    "Permutation test results of attrition among traditional arm borrowers",
#    "Permutation test results of attrition among non-traditional arm borrowers",
#    "Permutation test results of non-attriting members of traditional and non-traditional arm borrowers",
#    "Permutation test results of non-attriting members of cattle and all other arm borrowers",
#    "Permutation test results of non-attriting members of cattle and large grace arm borrowers",
  "Permutation test results of rejection", 
    "Permutation test results of rejection among traditional arm", 
    "Permutation test results of rejection among non-traditional arm",
    "Permutation test results of rejecters, traditional vs. non-traditional arm",
  "Permutation test results of group rejection", 
    "Permutation test results of group rejection among traditional arm", 
    "Permutation test results of group rejection among non-traditional arm",
    "Permutation test results of group rejecters, traditional vs. non-traditional arm",
  "Permutation test results of individual rejection", 
    "Permutation test results of individual rejection among traditional arm", 
    "Permutation test results of individual rejection among non-traditional arm",
    "Permutation test results of individual rejecters, traditional vs. non-traditional arm",
    "Permutation test results of group rejection in traditional arm vs. participants in non-traditional arm",
    "Permutation test results of rejecters, cattle vs. non-cattle arms",
    "Permutation test results of rejecters, cattle vs. large grace arms",
    "Permutation test results of borrowers, cattle vs. non-cattle arms",
    "Permutation test results of borowers, cattle vs. large grace arms",
    "Permutation test results of arm assignment, traditional vs. non-traditional arms"
    )
TabLabel1 <- paste("tab1", HeaderDescription)
TabLabel2 <- paste("tab2", HeaderDescription)
TabLabel3 <- paste("tab3", HeaderDescription)
