<<permutation tables>>=
tb1 <- "\\hfil\\begin{minipage}[t]{14cm}\\hfil\\textsc{\\normalsize Table \\refstepcounter{table}\\thetable: "
tb2 <- "}\\\\\\setlength{\\tabcolsep}{.5pt}\\setlength{\\baselineskip}{8pt}\\renewcommand{\\arraystretch}{.50}\\hfil\\begin{tikzpicture}\\node (tbl) {\\input{"
tb3 <- "}};\\end{tikzpicture}\\\\\\begin{tabular}{>{\\hfill\\scriptsize}p{1cm}<{}>{\\hfill\\scriptsize}p{.25cm}<{}>{\\scriptsize}p{12cm}<{\\hfill}}Source:& \\multicolumn{2}{l}{\\scriptsize Estimated with GUK administrative and survey data.}\\\\ Notes: & 1. & \\textsf{R}'s package \\textsf{coin} is used for baseline mean covariates to conduct approximate permutation tests. Number of repetition is set to "
#tb4 <- ". Step-down method is used to adjust for multiple testing of a multi-factor grouping variable. \\textsf{Attrited} and \\textsf{Nonattrited} columns show means of each group. For \\textsf{Arm}, proportions of non-traditional arm are given. \\\\& 2. & ${}^{***}$, ${}^{**}$, ${}^{*}$ indicate statistical significance at 1\\%, 5\\%, 10\\%, respetively. Standard errors are clustered at group (village) level.  \\\\& 3. & See the footnote of \\textsc{Table \\ref{tab MainTextIRjecters}} for description of variables. \\end{tabular}\\end{minipage}\\\\\\vspace{2ex}"
tb42 <- ". Step-down method is used to adjust for multiple testing of a multi-factor grouping variable. The second and third columns show means of each group. For \\textsf{Arm}, proportions of non-traditional arm between two groups are tested. \\\\& 2. & \\textsf{p-value.lower}, \\textsf{p-value.mid}, \\textsf{p-value.upper} indicate lower-bound, mid point value, and upper-bound of the $p$ values for observed test statistic and the null distribution, expressed in per centage units. \\\\& 3. & "
tb41 <- paste(tb42, "See the footnote of \\textsc{Table \\ref{tab MainTextIRjecters}} for description of variables. \\end{tabular}\\end{minipage}\\\\\\vspace{2ex} ")
tb43 <- ".\\\\& 2. &  See footnotes of \\textsc{Table \\ref{tab1 Permutation test results of rejection}} for description of variables. \\end{tabular}\\end{minipage}\\\\\\vspace{2ex}"
tb44 <- ".\\\\& 2. &  See footnotes of \\textsc{Table \\ref{tab1 Permutation test results of rejection among traditional arm}}. \\end{tabular}\\end{minipage}\\\\\\vspace{2ex}"
tb45 <- paste(tb42, "Contrasts between \\textsf{cattle} arm and other arms. See the footnote of \\textsc{Table \\ref{tab MainTextIRjecters}} for description of variables. \\end{tabular}\\end{minipage}\\\\\\vspace{2ex} ")
for (k in 1:3) 
  for (i in 1:length(HeaderDescription))
    assign(paste0("Tb", k, i), 
      paste0(
        tb1
        , 
        HeaderDescription[i]
        ,
        paste0("\\label{", get(paste0("TabLabel", k))[i], "}")
        ,
        tb2
        , 
        paste0(pathsavePerm, addtofilename[i], c("", "Full", "DropGroupRejecters")[k],
          "PermutationTestResultso800.tex")
        , 
        tb3
        ,
        PermRepTimes
        ,
        #if (i %in% c(1, 5, 11, 17, 21, 25)) tb42 else tb41
        if (i==17) 
          paste0(tb42, TabVariableDescription, PrefTestsDefinitions1, "\\end{tabular}\\end{minipage}\\\\\\vspace{2ex}") else 
        if (i %in% grep("non-catt", HeaderDescription)) # 30, 32 
          tb45 else 
        if (i %in% c(1, 5, 11, 18, 21, 25)) 
          tb43 else 
          tb44
        )
      )
@
