subst.tablePerm <- matrix(
  c("^Arm$", "Prop. of non-\\\\textsf{Traditional} arms",
    "HeadA.*", "Head age",
    "HHsize", "Household size",
    "HeadLi.*", "Head literate",
    "FloodI.*", "Flood at baseline",
    "NLHA.*", "Household asset amount",
    "PAss.*", "Productive asset amount",
    "Lives.*", "Livestock value",
    "NumC.*", "Number of cattle holding",
    "^NetValue$", "Net asset value",
    "^NetBroadValue$", "Broad net asset value",
    "Risk.*", "Risk preference value",
    "TimePr.*1.*", "Time preference value 1",
    "TimePr.*2.*", "Time preference value 2",
    "^PresentB.*", "Present bias"), byrow = T, ncol = 2)
