subst.tableA <- matrix(
  c("Arm|povertystatus|^se\\$.*|Schooling|sex|dummy", "",
    "I\\((.*?)\\)", "\\1",
    "factor\\((.*?)\\)", "\\1",
    "Time.?2", "rd 2",
    "Time.?3", "rd 3",
    "Time.?4", "rd 4",
    "RMvalue.(.*)", "6M \\1",
    "RM(.*)", "6M \\1",
    "[rR]epay$", "repayment",
    "Repayment", "repayment",
    "dummy", "",
    "LargeSize", "Upfront",
    "Cow", "Cattle",
    "Cattles", "Cattle", # this is added because the above line changes Cows => Cattles
    "NetSaving", "net saving",
    "Other", "other member ",
    "AmountFilled0", "land value$_{1}$",
    "HAss.*", "household asset value$_{1}$",
    "PAss.*", "productive asset value$_{1}$",
    "TotalImp.*", "livestock value$_{1}$",
    "NumCows0", "cattle holding$_{1}$",
    "TotalVal.*", "total asset value$_{1}$",
    "Net2?Val.*", "net asset value$_{1}$",
    "TotalHHLa.*", "household labour income$_{1}$",
    "TotalRev.*", "farm revenue$_{1}$",
    "PCExpe.*", "per capita consumption$_{2}$",
    "TotalExpe.*", "household consumption$_{2}$",
    "\\.", " $\\\\times$ ",
    "Lag(.*)", "\\1$_{t-1}$",
    "HeadLiteracy", "Head literate",
    "HeadAge", "Head age",
    "^OtherR.*d\\$", "Mean other repayment$",
    "^CumR.*d\\$", "Cumulative repayment$",
    "^CumR.*e\\$", "Cumulative repayment rate$",
    "^CumR.*Q\\$", "Cumulative repayment rate$^{2}",
    "^CumN.*g\\$", "Cumulative net saving$",
    "CumOtherO.*d\\$", "Other cumulative repayments$",
    "CumOtherR.*e\\$", "Other cumulative repayment rate$",
    "CumOtherR.*Q\\$", "Other cumulative repayment rate$^{2}",
    "MeanCumGroupNet.*g\\$", "Per member cumulative group net saving (1000Tk)$",
    "instruments \\((.*?)\\)", "IV: \\1",
    "MeanG.*g\\$", "Per member group net saving$",
    "\\^2", "$^{2}$",
    "Junior", "Secondary",
    "High", "College"), byrow = T, ncol = 2)
