## Table-footnote text pieces for HTML (.Rmd) manuscript tables.
## Lean replacement for TableFootnotePiecesHTML.R: keeps only the 12 objects
## actually used by the .Rmd pipeline --
##   EstimationGUK_Tufte.Rmd (+ subsection_Schooling.rmd, subsubsection_NetAssets.rmd,
##   ANCOVAEstimationFile3.R), EstimationMemo_Tufte.Rmd, ReadAndCleanData_Tufte.Rmd.
## The 26 unused pieces in TableFootnotePiecesHTML.R were dropped.

TabVariableDescription <- "`Head literate` is an indicator variable of household head literacy. `Head age` is age of household head. `Household size` is total number of household members. `Flood at baseline` is an indicator variable of flood exposure. `Household asset amount` and `Productive asset amount` are amount of non-livestock household and productive assets, respectively, in BDT. `Livestock value` is BDT value of all livestock holding beyond cattle. `Number of cattle holding` is number of cattle holding. `Net asset value` is net asset values in BDT using asset items observed in all 4 rounds. `Broad net asset value` is net asset values in BDT for all asset items. `Attrited` indicates attrition rates in the household survey, and `GRejected` and `IRejected` show group rejection rates and individual rejection rates to the lending program. `Non-attriting borrowers` indicates the ratio of non-attriting borrowers to all borrowers. Because attrition and rejection are separate events, a household can reject and attrit, so non-attrited borrowers $\\geqslant$ total - (rejected members + attrited members). USD 1 is about BDT 80."
TabFNAncovaTop.a <- "ANCOVA estimates using administrative and survey data. Post treatment regressands are regressed on categorical variables, pre-treatment regressand and other covariates."
TabFNAncovaTop.b <-  "`FloodInRd1` and `HeadLiterate0` are indicator variables for the presence of self reported damage by a flood at the baseline, and literacy of household head, respectively. `HHsize0` is household size at the baseline."
TabFNAncovaTop.c <-  "We annotate the number of periods that a household is observed with `T`. The total number of households is shown for each values of `T`. `T=4` indicates the number of households with complete panel information, `T=3` indicates number of households observed three times, `T=2` indicates the number of households observed twice. `N` indicates total number of observations used in ANCOVA estimation, or `N$=$1$\\\times$(T=2)+2$\\\times$(T=3)+3$\\\times$(T=4)`. "
TabFNAncovaTop <- paste(TabFNAncovaTop.a, TabFNAncovaTop.b, TabFNAncovaTop.c)
TabFN1stCol <- "Interaction terms of dummy variables are demeaned before interacting. The first column gives mean and standard deviation (in parenthesises) of each covariates before demeaning."
TabFNPval <- "$P$ values in percentages in parenthesises. Standard errors are clustered at group (village) level."
TabFNArm <- "`Large`, `LargeGrace`, `Cattle` are indicator variables of the `Large`, `Large grace`, and `Cattle` arms, respectively. The default arm category is `Traditional` arm."
TabFNAttributes <- "`Upfront` is an indicator variable of the arm with an upfront large disbursement, `WithGrace` is an indicator variable of the arm with a grace period, `InKind` is an indicator variable of the arm which lends a heifer."
TabFNRound234 <- "`rd2, rd3, rd4` are dummy variables for second, third, and fourth round of survey."
TabFNSch <- "`Secondary` and `College` are indicator variables of secondary schooling (ages 13-15) and tertiary schooling (ages 16-18), both at the time of baseline. Default category is primary (ages 05-12)."
PrefTestsDefinitions1 <- "`Risk preference` is the respondent's choice of the acceptable minimum excess monetary value of the risky option over a certainty option. Lower values indicate a greater risk tolerance. `Time preference 1` is the respondent's choice of the acceptable minimum excess monetary value in 3 months that is no smaller than present monetary benefit, and `Time preference 2` is the the minimum excess value in 1 year and 3 months that is no smaller than monetary benefits of 1 year from now. Lower values indicate a greater patience. If a respondent's `Time preference 1` is greater than `Time preference 2`, the respondent is considered to be present-biased. `Present bias` is an indicator function that takes the value of 1 if the respondent is considered to be present-biased, 0 otherwise."
